services:
  app_test:
    build:
      context: .
      dockerfile: Dockerfile.Apache.TEST.PROD
    image: ${PROJECT_NAME_LOWER}_test
    container_name: ${PROJECT_NAME}_test
    hostname: ${PROJECT_NAME}_test
    restart: always
    environment:
      - IMAGE_DATE=${IMAGE_DATE}
      - IMAGE_VERSION=${IMAGE_VERSION}
      - PUSH_SHA=${PUSH_SHA}
      - APP_ENV=TEST
      - APP_NAME=${APP_NAME}
      - LOCALLOG=true
      - REDIS_SERVER=redisserver_test
      - REDIS_PORT=6379
      - REDIS_CACHETIME=3600
      - DB_HOST=mariadb_test
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    working_dir: /var/www/html
    depends_on:
      - mariadb_test
      - redisserver_test
    networks:
      - internal_test
      - caddy
    labels:
      caddy: ${PROJECT_NAME}.test.bpmspace.net
      caddy.reverse_proxy: "{{upstreams http}}"

  mariadb_test:
    image: mariadb:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    container_name: ${PROJECT_NAME}-mariadb_test
    hostname: ${PROJECT_NAME}-mariadb_test
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb-data_test:/var/lib/mysql
    networks:
      - internal_test

  phpmyadmin_test:
    image: phpmyadmin:latest
    container_name: ${PROJECT_NAME}-phpmyadmin_test
    hostname: ${PROJECT_NAME}-phpmyadmin_test
    restart: always
    environment:
      - PMA_HOST=mariadb_test
      - MEMORY_LIMIT=1516M
      - UPLOAD_LIMIT=1024M
    depends_on:
      - mariadb_test
    networks:
      - internal_test
      - caddy
    labels:
      caddy: pma-${PROJECT_NAME}.test.bpmspace.net
      caddy.reverse_proxy: "{{upstreams 80}}"

  redisserver_test:
    image: redis/redis-stack:latest
    container_name: ${PROJECT_NAME}-redisserver_test
    hostname: ${PROJECT_NAME}-redisserver_test
    restart: always
    volumes:
      - redis-data_test:/data
    networks:
      - internal_test

  phpredisadmin_test:
    image: erikdubbelboer/phpredisadmin
    container_name: ${PROJECT_NAME}-phpredisadmin_test
    hostname: ${PROJECT_NAME}-phpredisadmin_test
    restart: always
    environment:
      - REDIS_1_HOST=redisserver_test
      - REDIS_1_NAME=${APP_NAME}
      - ADMIN_USER=${REDIS_ADMIN_USER}
      - ADMIN_PASS=${REDIS_ADMIN_PASS}
    networks:
      - internal_test
      - caddy
    labels:
      caddy: pmr-${PROJECT_NAME}.test.bpmspace.net
      caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  mariadb-data_test:
    driver: local
  redis-data_test:
    driver: local

networks:
  internal_test:
    driver: bridge
  caddy:
    external: true
