services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile.Apache.DEV
    image: ${PROJECT_NAME_LOWER}_dev
    container_name: ${PROJECT_NAME}_dev
    hostname: ${PROJECT_NAME}_dev
    restart: always
    environment:
      - IMAGE_DATE=not set in DEV
      - IMAGE_VERSION=not set in DEV
      - PUSH_SHA=not set in DEV
      - APP_ENV=DEV
      - APP_NAME=${APP_NAME}
      - LOCALLOG=true
      - REDIS_SERVER=redisserver_dev
      - REDIS_PORT=6379
      - REDIS_CACHETIME=3600
      - DB_HOST=mariadb_dev
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - './www:/var/www/html'
      - './scripts:/var/scripts'
    working_dir: /var/www/html
    depends_on:
      - mariadb_dev
      - redisserver_dev
    networks:
      - internal_dev
      - caddy
    labels:
      caddy: ${PROJECT_NAME}.dev.bpmspace.net
      caddy.reverse_proxy: "{{upstreams http}}"

  mariadb_dev:
    image: mariadb:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    container_name: ${PROJECT_NAME}_mariadb_dev
    hostname: ${PROJECT_NAME}_mariadb_dev
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb-data_dev:/var/lib/mysql
    networks:
      - internal_dev

  phpmyadmin_dev:
    image: phpmyadmin:latest
    container_name: ${PROJECT_NAME}_phpmyadmin_dev
    hostname: ${PROJECT_NAME}_phpmyadmin_dev
    restart: always
    environment:
      - PMA_HOST=mariadb_dev
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
    depends_on:
      - mariadb_dev
    networks:
      - internal_dev
      - caddy
    labels:
      caddy: pma-${PROJECT_NAME}.dev.bpmspace.net
      caddy.reverse_proxy: "{{upstreams 80}}"

  redisserver_dev:
    image: redis/redis-stack:latest
    container_name: ${PROJECT_NAME}_redisserver_dev
    hostname: ${PROJECT_NAME}_redisserver_dev
    restart: always
    volumes:
      - redis-data_dev:/data
    networks:
      - internal_dev

  phpredisadmin_dev:
    image: erikdubbelboer/phpredisadmin
    container_name: ${PROJECT_NAME}_phpredisadmin_dev
    hostname: ${PROJECT_NAME}_phpredisadmin_dev
    restart: always
    environment:
      - REDIS_1_HOST=redisserver_dev
      - REDIS_1_NAME=${APP_NAME}
      - ADMIN_USER=${REDIS_ADMIN_USER}
      - ADMIN_PASS=${REDIS_ADMIN_PASS}
    networks:
      - internal_dev
      - caddy
    labels:
      caddy: pmr-${PROJECT_NAME}.dev.bpmspace.net
      caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  mariadb-data_dev:
    driver: local
  redis-data_dev:
    driver: local

networks:
  internal_dev:
    driver: bridge
  caddy:
    external: true
