services:
  ${PROJECT_NAME}_DEV:
    build:
      context: .
      dockerfile: Dockerfile.Apache.DEV
    container_name: ${PROJECT_NAME}_DEV
    hostname: ${PROJECT_NAME}_DEV
    restart: always
    environment:
      - IMAGE_DATE=not set in DEV
      - IMAGE_VERSION=not set in DEV
      - PUSH_SHA=not set in DEV
      - APP_ENV=DEV
      - APP_NAME=${APP_NAME}
      - LOCALLOG=true
      - REDIS_SERVER=${PROJECT_NAME}-redisserver_DEV
      - REDIS_PORT=6379
      - REDIS_CACHETIME=3600
    volumes:
      - './www:/var/www/html'
      - './scripts:/var/scripts'
    working_dir: /var/www/html
    networks:
      - ${PROJECT_NAME}_DEV
      - caddy
    labels:
      caddy: ${PROJECT_NAME}.dev.bpmspace.net
      caddy.reverse_proxy: "{{upstreams http}}"

  ${PROJECT_NAME}-redisserver_DEV:
    image: redis/redis-stack:latest
    container_name: ${PROJECT_NAME}-redisserver_DEV
    hostname: ${PROJECT_NAME}-redisserver_DEV
    restart: always
    volumes:
      - ${PROJECT_NAME}-redis-data_DEV:/data
    networks:
      - ${PROJECT_NAME}_DEV

  ${PROJECT_NAME}-phpredisadmin_DEV:
    image: erikdubbelboer/phpredisadmin
    container_name: ${PROJECT_NAME}-phpredisadmin_DEV
    hostname: ${PROJECT_NAME}-phpredisadmin_DEV
    restart: always
    environment:
      - REDIS_1_HOST=${PROJECT_NAME}-redisserver_DEV
      - REDIS_1_NAME=${APP_NAME}
      - ADMIN_USER=${REDIS_ADMIN_USER}
      - ADMIN_PASS=${REDIS_ADMIN_PASS}
    networks:
      - ${PROJECT_NAME}_DEV
      - caddy
    labels:
      caddy: pmr-${PROJECT_NAME}.dev.bpmspace.net
      caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  ${PROJECT_NAME}-redis-data_DEV:
    driver: local

networks:
  ${PROJECT_NAME}_DEV:
    driver: bridge
  caddy:
    external: true
